name: Main Front Pipeline
on:
    push:
        branches:
            - main
jobs:
    avoid_conflicts:
        runs-on: ubuntu-latest
        permissions:
            actions: write
        steps:
            - name: Cancel conflicting runs
              uses: styfle/cancel-workflow-action@0.9.1
              with:
                  access_token: ${{ github.token }}
    deploy:
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'
        timeout-minutes: 10
        steps:
            - name: Deploy to Contabo server
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.CONTABO_HOST }}
                  username: ${{ secrets.CONTABO_USERNAME }}
                  password: ${{ secrets.CONTABO_PASSWORD }}
                  port: 22
                  script: |
                      set -e
                      cd services/workblokfront
                      git checkout main
                      git pull https://davilasanvilar:${{ secrets.GIT_PAT }}@github.com/VilaDevCorp/workblok-front.git
                      yarn install
                      yarn build
                      rm -rf /var/www/workblok_dist
                      mv dist /var/www/workblok_dist